### ISSUE TITLE
User cannot upload 30GB file

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/w3up#1208]
Don't have a ton of detail here but a user reached out to the support email with an issue uploading a large, 30GB file. Here's the errors. If anyone else encounters something similar please comment so we can work with you to understand what's going on.

<img width="1254" alt="Screenshot 2023-11-29 at 9 49 35 PM" src="https://github.com/web3-storage/w3up/assets/11778450/4a965f38-d3e5-44de-8245-c644cd9edeb2">
<img width="673" alt="Screenshot 2023-11-29 at 9 49 54 PM" src="https://github.com/web3-storage/w3up/assets/11778450/3f2ec7e6-a445-40d3-b51a-106fb2c45da4">

```[tasklist]
### Tasks
- [ ] https://github.com/web3-storage/w3up/pull/1227
- [ ] https://github.com/web3-storage/fr32-sha2-256-trunc254-padded-binary-tree-multihash/pull/29
- [ ] release upload-client latest to console
```

**Comment by Gozala** [comment]
There seems to be multiple issues here at play. Looking into this I discovered that we keep using increasingly more memory and at around 4GB wasm starts to fail.

One issue is it looks like we fail do dealocate memory tracked by https://github.com/web3-storage/fr32-sha2-256-trunc254-padded-binary-tree-multihash/issues/28

But even if I remove the Piece hashing entirely here

https://github.com/web3-storage/w3up/blob/153da70e06e9146783193e81cd85294eafdc17e8/packages/upload-client/src/index.js#L133-L138

We still keep using more and more memory around 15GB when uploading 17GB file and we climb up really quickly around when only 6% is processed

If I comment following lines out, memory use is under 200MB so there is something wrong going on within the commented block

https://github.com/web3-storage/w3up/blob/153da70e06e9146783193e81cd85294eafdc17e8/packages/upload-client/src/store.js#L58-L133

**Comment by Gozala** [comment]
I'm focusing on https://github.com/web3-storage/fr32-sha2-256-trunc254-padded-binary-tree-multihash/issues/28

@gobengo if you'll have time maybe you can take a look at the other leak in the store.js file

**Comment by gobengo** [comment]
I'm hopeful that the root cause of this was https://github.com/web3-storage/w3up/pull/1227 which has been released in upload-client.
@travis will deploy to console sometime today and it should include that new upload-client, and then I'll test this again. (I tested a bit ago with a 6GB file and I reproduced the error still)

**Comment by gobengo** [comment]
I just tried a 6GB file on console.web3.storage after releasing a lot of the memory fixes from this week and I still get
![image](https://github.com/web3-storage/w3up/assets/171782/327fd420-e298-4e25-9aea-2ea2bc54cfa4)

**Comment by gobengo** [comment]
I was able to upload a 6GB file just now even though it used to trigger this same error. I am hopeful 🤞🏻 this might be fixed. @dchoi27 could you ask the end-user to retest?

**Comment by dchoi27** [comment]
Ah unfortunately they asked to have their account deleted when this didn't work. Maybe if we get 1-2 other points of validation we can close this.

**Comment by dchoi27** [comment]
ok - the original user got back to me and confirmed it worked! closing this
