### ISSUE TITLE
w3up-client README links to archived/old w3up-client docs

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3up#1215]
Discovered while devving:
* https://github.com/web3-storage/w3up/pull/1214

Context
* [this README](https://github.com/web3-storage/w3up/blame/main/packages/w3up-client/README.md) was added to that monorepo 9 months ago based on this https://github.com/web3-storage/w3up-client
* and that old w3up-client repo is archived (it was a prototype) and the API has changed several times in the code, but the README still documents some stuff from the old api

Acceptance Criteria:
* the w3up monorepo /packages/w3up-client/README.md https://github.com/web3-storage/w3up/blame/main/packages/w3up-client/README.md
  * [x] should no longer contain links to the tsdoc for the old lib https://web3-storage.github.io/w3up-client/classes/client.Client.html#uploadFile
    * should instead include links to the tsdoc from the w3up monorepo, e.g. https://web3-storage.github.io/w3up/modules/_web3_storage_w3up_client.html
```[tasklist]
### Tasks
- [x] remove links to old w3up-client tsdoc
- [ ] https://github.com/web3-storage/w3up/pull/1218
- [x] ensure released at reflected at https://www.npmjs.com/package/@web3-storage/w3up-client
```

**Comment by gobengo** [comment]
verified that README here https://www.npmjs.com/package/@web3-storage/w3up-client
links to docs like https://web3-storage.github.io/w3up/classes/_web3_storage_w3up_client.Client.html
