### ISSUE TITLE
Tracking w3up work 🆙

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3up#650]
### **Sprint runs until April 14**

**Misc work is ordered by priority**
- [x] update beta w3ui site to reflect the current world @travis 
        https://github.com/web3-storage/w3ui-website/pull/14
- [ ] #655
- [x] fast auth email confirmation
        https://github.com/web3-storage/w3protocol/pull/602 @travis 
        extra calls to access claim - perhaps doesn't scale <- larger convo
- [ ] #652 (Vasco to add details)
- [ ] https://github.com/web3-storage/w3protocol/issues/690 @dchoi27 and maybe Alan
- [ ] receipts and ucanto upgrade @Gozala  + @vasco-santos 
       https://github.com/web3-storage/ucanto/pull/271
       https://github.com/web3-storage/ucanto/pull/266
       https://github.com/web3-storage/ucanto/pull/272
       https://github.com/web3-storage/ucanto/pull/273
       https://github.com/web3-storage/ucanto/pull/274
       https://github.com/web3-storage/w3infra/pull/187
       https://github.com/web3-storage/w3infra/issues/189
       https://github.com/web3-storage/w3up/issues/735
- [ ] #703 (will begin implementation in phase 4 but will not be complete)
- [ ] #702
- [x] moving w3up-client to w3protocol mono repo @gobengo https://github.com/web3-storage/w3protocol/issues/648
- [ ] Land BYOP - https://github.com/web3-storage/w3up-client/pull/74 @alanshaw
- [ ] #689
- [x] #682
- [x] Fix https://github.com/web3-storage/w3protocol/issues/641
- [x] https://github.com/web3-storage/w3up/issues/704 (start week of April 10th)
- [ ] https://github.com/web3-storage/w3up/issues/711 ⚠ (depends on prev work, example: provider <> spaces) 
       - [x] https://github.com/web3-storage/w3up/issues/684
       - [ ] https://github.com/web3-storage/w3up/pull/744/files
- [ ] https://github.com/elastic-ipfs/elastic-ipfs/issues/25 (vasco to start in the week of April 10th)

**metrics and monitoring**
- [ ] P1 Fix https://github.com/web3-storage/w3protocol/issues/623 (bengo has been working on)
- [ ] P1 #709 (potentially gozala)
- [ ] P1 #710 (potentially olizilla, alan, vasco)
- [ ] metrics
       - [ ] access api  https://github.com/web3-storage/w3infra/pull/182
       - [ ] time interval usage per space https://github.com/web3-storage/w3infra/issues/190
- [ ] https://github.com/web3-storage/w3infra/issues/170 (blocked until April 17th)
- [ ] https://github.com/web3-storage/w3infra/pull/191

**migrating away from IPFS Cluster**
- [ ] https://github.com/web3-storage/backup/issues/1
       - web3.storage (status: 🟡 in progress 🟡 )
       - nft.storage (status: 🔴 not started 🔴 )

**Comment by heyjay44** [comment]
**Phase 4 nice to haves (move to backlog if not complete by end of phase 4)**
- [ ] security phrase for email validation 
        https://github.com/web3-storage/w3protocol/issues/347
        https://github.com/web3-storage/w3protocol/pull/432
- [ ] add docs page and link to open tickets 
        https://github.com/web3-storage/w3ui/issues/398
- [ ] Console warnings about public and permanent data 
        https://github.com/web3-storage/w3ui/issues/464
- [ ] #651 

Backlog:
- [ ] `space/info` should return provider https://github.com/web3-storage/w3protocol/issues/515
- [ ] Complete single service URL work https://github.com/web3-storage/w3protocol/issues/325
- [ ] Increase freeway limits based on new worker sub-request limits
- [ ] Redesign w3up logo
- [ ] https://github.com/web3-storage/w3protocol/issues/520
- [ ] There are tons of smaller less important issues in https://github.com/web3-storage/w3protocol/issues 
- [ ] Implement revocations https://github.com/web3-storage/w3protocol/issues/327
- [ ] Delegate/claim specific capabilities
- [ ] Persist pet name for space when claiming on another agent
- [ ] UX for authorize in w3console (allow authorize at point of upload)
- [ ] Read CAR by CAR CID
- [ ] Figure out how to extract NFT.Storage specific metrics
- [ ] metrics tracking - usage over time??
- [ ] upload progress bar (estimated work: 1 week)
        https://github.com/web3-storage/w3ui/issues/378
- [ ] gateway q: can we turn on gzip and save some bandwidth?
