### ISSUE TITLE
decommission `voucher/*` protocol (superceded by `access/*` and `provider/*` et al)

### ISSUE THREAD

**Issue by gobengo** [web3-storage/w3up#700]
```[tasklist]
### Tasks
- [ ] remove code from access-client that relies on voucher protocol
- [ ] remove code from access-api that implements voucher protocol
    - [ ] test that invoking `voucher/*` results in a helpful message saying to try using the new `access/authorize` and `provider/add` flows (idea via @Gozala)
- [ ] remove code from `@web3-storage/capabilities` that are the voucher protocol capabilityParsers

```

**Comment by Gozala** [comment]
> remove code from access-api that implements voucher protocol

I would change it to `update voucher protocol handlers in `access-api` to return error telling to migrate to `provider` protocol.

**Comment by Gozala** [comment]
> remove code from @web3-storage/capabilities that are the voucher protocol capabilityParsers

I think I'd mark those as deprecated for now and remove in the future along with voucher protocol handlers
