### ISSUE TITLE
Tracking saturn integration 🪐

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3up#754]
```[tasklist]
### Tasks
- [ ] https://github.com/web3-storage/freeway/issues/34
- [ ] https://github.com/web3-storage/w3up/issues/786
- [ ] https://github.com/web3-storage/freeway/issues/33
- [ ] https://github.com/web3-storage/freeway/issues/32
- [ ] https://github.com/web3-storage/w3up/issues/743
- [ ] https://github.com/web3-storage/w3infra/issues/188
- [ ] https://github.com/web3-storage/w3up/issues/751
- [ ] https://github.com/web3-storage/w3up/issues/752
```

**Comment by heyjay44** [comment]
Closing as this is on pause.
