### ISSUE TITLE
[Tracking] Keyring 

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3up#94]
Draft of roadmap:
- [ ] userflows (offline, online, all variations) - Hugo
- [ ] once user flows are confirmed, design implementation.
- [ ] Setup CI/CD for access-ws package
