### ISSUE TITLE
[Tracking] w3up phase 1

### ISSUE THREAD

**Issue by heyjay44** [web3-storage/w3up#97]
# w3up phase 1 initiative

Notion Doc: https://www.notion.so/w3up-improvements-e6d14daea22748c29b261fcf013013f3
Project Board: https://github.com/orgs/web3-storage/projects/13/views/5
Milestone: `w3up phase 1`

## w3protocol
- [x] Docs for each UCAN capability used by our services (@gozala + @yusefnapora)
       Reference docs (#172)
       Doc comments (#159)
       Example usage docs
- [x] #24 
- [ ] #151
- [ ] #167 (@hugomrdias + @alanshaw) (2)
- [x] #200

## access-api:
- [x] #111
- [ ] #114 (2)
- [x] #115
- [x] #122 
- [ ] #199 (2)
- [x] #129 
- [ ] #180 (2)

## access-client
- [x] #153
- [x] Support full account delegation ( @alanshaw + @ice-breaker-tg )
- [x] #208
- [x] #193
- [ ] Support https://github.com/web3-storage/specs/blob/main/w3-space.md
- [x] https://github.com/web3-storage/w3protocol/issues/251 @yusefnapora 
- [x] https://github.com/web3-storage/w3protocol/issues/237
- [x] setCurrentSpace
- [x] getCurrentSpace
- [x] proofs

 
## upload-api
- [ ] #152 (@vasco-santos / @olizilla)
- [x] Integrate w3access agent + ucanto 0.9 (@vasco-santos / @olizilla)
- [x] Define and document DB schema (@olizilla + @vasco-santos + ice-breaker-tg + everyone) https://github.com/web3-storage/upload-api/issues/25
- [x] Pagination for uploads listing (@vasco-santos + @olizilla) https://github.com/web3-storage/upload-api/issues/16
- [ ] Allow listing of stored cars that are not associated with an “upload” (could be parameter on upload listing) (@vasco-santos + @olizilla) https://github.com/web3-storage/upload-api/issues/41
- [x] Pagination for store listing (@vasco-santos + @olizilla) https://github.com/web3-storage/upload-api/issues/16
- [x] Delete from store/uploads list(?) (@vasco-santos + @olizilla)
- [ ] Add invocation receipts (@gozala + @hugomrdias)
- [ ] Add API for retrieving Filecoin deals for a given data CID (@alanshaw + @ice-breaker-tg) (2)
- [x] Size constraint for pre-signed URL (@ice-breaker-tg + @vasco-santos) https://github.com/web3-storage/upload-api/issues/38
- [ ] ~~Disallow create many accounts with the same email (@hugomrdias + @alanshaw)~~ (2)

## upload-client
- [x] #150
- [x] https://github.com/web3-storage/w3protocol/issues/250 @yusefnapora 
- [x] update api to take `proof` and `issuer`
- [x] https://github.com/web3-storage/w3protocol/issues/237
- [ ]  update api to take proof and issuer

## w3up-client
- [x] https://github.com/web3-storage/w3up-client/issues/56 (@alanshaw)
- [x] https://github.com/web3-storage/w3protocol/issues/273 @yusefnapora 
- [x] https://github.com/web3-storage/w3protocol/issues/281 @heyjay44 @yusefnapora 

## w3up-cli
- [x] Consume upload-client https://github.com/web3-storage/w3cli/pull/20 ( @olizilla + @alanshaw )
- [x] Support full account delegation ( @olizilla + @vasco-santos ) (2)

## w3ui

- [x] https://github.com/web3-storage/w3ui/issues/127 (@alanshaw)
- [x] https://github.com/web3-storage/w3ui/pull/129
- [ ] Moved to Phase 2: https://github.com/web3-storage/w3ui/issues/120 @travis 
- [x] https://github.com/web3-storage/w3ui/issues/138 @yusefnapora 

## JS UnixFS
- [ ] https://github.com/web3-storage/w3up-client/issues/54 ( @Gozala + @alanshaw )

## ucanto
- [ ] option to disable error stacks in ucanto when serialising responses 
- [ ] ucanto server catch should be able to catch and override the response to return a generic 500 error 
- [x] fix type incompatibility between `URI<"did">` and `did:${string}:${string}`

## Refs
https://hackmd.io/@alanshaw/ByJX1azrj
https://www.notion.so/2022-11-03-w3up-meeting-0076890d8e634579b05cff7108f03039
https://www.notion.so/2022-10-19-User-experience-and-IPFS-Camp-Deliverables-ec8e843d7659449ab278f81637affcf0

**Comment by hugomrdias** [comment]
# Access client

- [ ] setCurrentAccount
- [ ] getCurrentAccount
- [ ] getProof(cap, accountDID?)

# Upload client

- [ ] update api to take `proof` and `issuer`
