### ISSUE TITLE
The Types Are Wrong!

### ISSUE THREAD

**Issue by travis** [web3-storage/w3up#982]
Plugging a couple of our libraries into https://arethetypeswrong.github.io/ shows that our types could use some improvements:

https://arethetypeswrong.github.io/?p=%40web3-storage%2Fw3up-client%409.0.0
https://arethetypeswrong.github.io/?p=%40web3-storage%2Faccess%409.0.0

<img width="990" alt="Screenshot 2023-10-18 at 4 59 13 PM" src="https://github.com/web3-storage/w3up/assets/1113/e7b52d77-d65d-47cc-a486-0585b04ced66">
<img width="805" alt="Screenshot 2023-10-18 at 4 59 01 PM" src="https://github.com/web3-storage/w3up/assets/1113/cccc4488-c4d3-4a21-98de-e7725666c314">

Fortunately they also have a wonderful key for the errors they show, with a helpful page for fixing each of them:

https://github.com/arethetypeswrong/arethetypeswrong.github.io#readme

We should fix the types on the most forward-facing stuff first because I think this is actively hampering downstream development with our libraries, and it would be good to check all of our libraries soon.

```[tasklist]
### Tasks
- [ ] https://github.com/web3-storage/w3up/pull/1004
- [ ] https://github.com/web3-storage/w3up/issues/1013
- [ ] https://github.com/web3-storage/w3up/issues/1015
- [ ] https://github.com/web3-storage/w3up/issues/1016
- [ ] https://github.com/web3-storage/w3up/pull/1014
```

**Comment by gobengo** [comment]
@travis will you plz review https://github.com/web3-storage/w3up/pull/1004 ? I think it may resolve this issue.

**Comment by gobengo** [comment]
After the fix from #1004, which affected how npm/pnpm are configured in package.jsons in a way that could affect the release process of our packages, I wanted to do a test release of a package. I just did it with did-mailto and the release went ok and I confirmed the new release of did-mailto resolves arethetypesworking errors as I expected https://github.com/web3-storage/w3up/issues/1013#issuecomment-1779827607

I chose did-mailto because it's the simplest package and in case things went haywire, I think it has the least external dependers.

I'm more worried about the other 3 packages (*-client) that I touched in this PR. https://github.com/web3-storage/w3up/pull/1012/files
Next I'll test one of them

**Comment by gobengo** [comment]
The original issue here shows arethetypesworking errors for the two packages of `@web3-storage/access` and `@web3-storage/w3up-client`.

I've now released new versions of each and tested that arethetypesworking is happier about them now
* access test https://github.com/web3-storage/w3up/issues/1015
* w3up-client test https://github.com/web3-storage/w3up/issues/1016

**Comment by gobengo** [comment]
Here are results of testing the other packages
* ✅ [@web3-storage/capabilities@11.0.0](https://arethetypeswrong.github.io/?p=%40web3-storage%2Fcapabilities%4011)
* ✅ [@web3-storage/did-mailto@2.0.2](https://arethetypeswrong.github.io/?p=%40web3-storage%2Fdid-mailto%402.0.2)
* [@web3-storage/filecoin-api@2.0.3](https://arethetypeswrong.github.io/?p=%40web3-storage%2Ffilecoin-api%402.0.3)
  * [ ] needs 2.0.3 released https://github.com/web3-storage/w3up/pull/1009
* @web3-storage/filecoin-client@latest
  * see [results for @web3-storage/filecoin-client@2.0.1](https://arethetypeswrong.github.io/?p=%40web3-storage%2Ffilecoin-client%402.0.1). It's almost all green except for an "💀 Resolution Failed" error for "@web3-storage/filecoin-client/chain-tracker"
    * [ ] needs this fix https://github.com/web3-storage/w3up/pull/1014
* [ ] upload-api
* [ ] upload-client

**Comment by gobengo** [comment]
@travis would you agree this issue is now resolved?
